name: 'Docker Deployment'
description: 'Start a Docker container on remote server'
inputs:
  host:  # id of input
    description: 'target host'
    required: true
  port:  # id of input
    description: 'target port'
    required: false
    default: '2376'
runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: create-certs.sh
      shell: bash
      env:
        CA_PEM: ${{secrets.CA_PEM}}
        CERT_PEM: ${{secrets.CERT_PEM}}
        KEY_PEM: ${{secrets.KEY_PEM}}
    - run: pull-and-start.sh
      shell: bash