name: 'Docker Deployment'
description: 'Start a Docker container on remote server'
inputs:
  host:
    description: 'target host'
    required: true
  port:
    description: 'target port'
    required: false
    default: '2376'
  ca-pem:
    description: 'ca.pem'
    required: true
  cert-pem:
    description: 'cert.pem'
    required: true
  key-pem:
    description: 'key.pem'
    required: true
  docker-compose-file:
    description: 'optional file which is merged with docker-compose.yml'
    required: false

runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: create-certs.sh
      shell: bash
      env:
        CA_PEM: ${{ inputs.ca-pem }}
        CERT_PEM: ${{ inputs.cert-pem }}
        KEY_PEM: ${{ inputs.key-pem }}
    - run: pull-and-start.sh
      shell: bash
      env:
        HOST: ${{ inputs.host }}
        PORT: ${{ inputs.port }}
        DOCKER_COMPOSE_FILE: ${{ inputs.docker-compose-file }}